# Generated by Django 3.2.4 on 2022-04-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_message_isread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='isRead',
        ),
    ]
